sudo: false
language: python
dist: xenial
python:
  - 3.8-dev
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements_dev.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: pytest --cov-report xml --cov=api api/tests
after_script: ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
